package agentctx

import (
	"fmt"
	"strings"
	"sync"
	"time"
)

// FileInfo describes a file tracked by the context engine.
type FileInfo struct {
	Name     string    `json:"name"`
	Path     string    `json:"path"`     // path inside container / workspace
	Size     int64     `json:"size"`
	Modified time.Time `json:"modified"`
	Preview  string    `json:"preview"`  // first N bytes of the file content
	IsOutput bool      `json:"isOutput"` // true if generated by the agent
}

// FileContext tracks uploaded, workspace, and generated files with thread safety.
type FileContext struct {
	mu             sync.RWMutex
	uploadedFiles  []FileInfo
	workspaceFiles []FileInfo
	generatedFiles []FileInfo
}

// NewFileContext creates an empty file context.
func NewFileContext() *FileContext {
	return &FileContext{
		uploadedFiles:  make([]FileInfo, 0),
		workspaceFiles: make([]FileInfo, 0),
		generatedFiles: make([]FileInfo, 0),
	}
}

// AddUploadedFile records a file that was uploaded by the user.
func (fc *FileContext) AddUploadedFile(info FileInfo) {
	fc.mu.Lock()
	defer fc.mu.Unlock()
	fc.uploadedFiles = append(fc.uploadedFiles, info)
}

// AddGeneratedFile records a file that was generated by the agent.
func (fc *FileContext) AddGeneratedFile(info FileInfo) {
	fc.mu.Lock()
	defer fc.mu.Unlock()
	info.IsOutput = true
	fc.generatedFiles = append(fc.generatedFiles, info)
}

// SetWorkspaceFiles replaces the current workspace file listing.
func (fc *FileContext) SetWorkspaceFiles(files []FileInfo) {
	fc.mu.Lock()
	defer fc.mu.Unlock()
	fc.workspaceFiles = make([]FileInfo, len(files))
	copy(fc.workspaceFiles, files)
}

// GetUploadedFiles returns a copy of the uploaded files list.
func (fc *FileContext) GetUploadedFiles() []FileInfo {
	fc.mu.RLock()
	defer fc.mu.RUnlock()
	out := make([]FileInfo, len(fc.uploadedFiles))
	copy(out, fc.uploadedFiles)
	return out
}

// GetWorkspaceFiles returns a copy of the workspace files list.
func (fc *FileContext) GetWorkspaceFiles() []FileInfo {
	fc.mu.RLock()
	defer fc.mu.RUnlock()
	out := make([]FileInfo, len(fc.workspaceFiles))
	copy(out, fc.workspaceFiles)
	return out
}

// GetGeneratedFiles returns a copy of the generated files list.
func (fc *FileContext) GetGeneratedFiles() []FileInfo {
	fc.mu.RLock()
	defer fc.mu.RUnlock()
	out := make([]FileInfo, len(fc.generatedFiles))
	copy(out, fc.generatedFiles)
	return out
}

// GetAllFiles returns a combined list of all tracked files.
func (fc *FileContext) GetAllFiles() []FileInfo {
	fc.mu.RLock()
	defer fc.mu.RUnlock()
	all := make([]FileInfo, 0, len(fc.uploadedFiles)+len(fc.workspaceFiles)+len(fc.generatedFiles))
	all = append(all, fc.uploadedFiles...)
	all = append(all, fc.workspaceFiles...)
	all = append(all, fc.generatedFiles...)
	return all
}

// formatSize returns a human-readable size string.
func formatSize(bytes int64) string {
	switch {
	case bytes >= 1<<20:
		return fmt.Sprintf("%.1fMB", float64(bytes)/float64(1<<20))
	case bytes >= 1<<10:
		return fmt.Sprintf("%.1fKB", float64(bytes)/float64(1<<10))
	default:
		return fmt.Sprintf("%dB", bytes)
	}
}

// FormatForSystemMessage returns a text description of current files
// suitable for injecting into the system prompt.
func (fc *FileContext) FormatForSystemMessage() string {
	fc.mu.RLock()
	defer fc.mu.RUnlock()

	total := len(fc.uploadedFiles) + len(fc.workspaceFiles) + len(fc.generatedFiles)
	if total == 0 {
		return ""
	}

	var sb strings.Builder
	sb.WriteString("Current workspace files:\n")

	for _, f := range fc.uploadedFiles {
		sb.WriteString(fmt.Sprintf("- %s (%s, uploaded)\n", f.Path, formatSize(f.Size)))
	}
	for _, f := range fc.workspaceFiles {
		sb.WriteString(fmt.Sprintf("- %s (%s)\n", f.Path, formatSize(f.Size)))
	}
	for _, f := range fc.generatedFiles {
		sb.WriteString(fmt.Sprintf("- %s (%s, generated)\n", f.Path, formatSize(f.Size)))
	}

	return strings.TrimRight(sb.String(), "\n")
}
