// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {agentctx} from '../models';
import {service} from '../models';
import {tools} from '../models';
import {context} from '../models';
import {sandbox} from '../models';
import {time} from '../models';

export function AddDiscoveredTool(arg1:string,arg2:model.DiscoveredToolRecord):Promise<boolean>;

export function ApproveToolPermission(arg1:string,arg2:string):Promise<void>;

export function BuildRunners():Promise<void>;

export function ClearHistory():Promise<void>;

export function ClearToolPermissionGrants(arg1:string):Promise<void>;

export function CtxEngine():Promise<agentctx.Engine>;

export function DenyToolPermission(arg1:string):Promise<void>;

export function ExportSessionSnapshot(arg1:string):Promise<service.SessionSnapshot>;

export function GetActiveSessionID():Promise<string>;

export function GetDeferredSurfaceDebug(arg1:string):Promise<service.DeferredSurfaceDebug>;

export function GetMode():Promise<string>;

export function GetOrCreateRun(arg1:string):Promise<service.SessionRun>;

export function GetRuntimeLSPStatus(arg1:string):Promise<service.RuntimeLSPStatus>;

export function GetSessionRunSnapshot(arg1:string):Promise<boolean>;

export function InvalidateRunner():Promise<void>;

export function IsRunning():Promise<boolean>;

export function IsSessionRunning(arg1:string):Promise<boolean>;

export function ListRuntimeTasks(arg1:string):Promise<Array<tools.RuntimeTaskSnapshot>>;

export function ListToolPermissionGrants(arg1:string):Promise<Array<model.RuntimePermissionGrant>>;

export function ListToolPermissionRequests(arg1:string):Promise<Array<tools.ToolPermissionRequest>>;

export function PruneDiscoveredToolsForSave(arg1:string,arg2:Array<model.DiscoveredToolRecord>):Promise<Array<model.DiscoveredToolRecord>>;

export function ReadRuntimeTaskOutput(arg1:string,arg2:number,arg3:number):Promise<tools.RuntimeTaskOutput>;

export function RemoveSession(arg1:string):Promise<void>;

export function ReplaceDiscoveredTools(arg1:string,arg2:Array<model.DiscoveredToolRecord>):Promise<void>;

export function RestoreSessionData(arg1:string,arg2:model.SessionData):Promise<void>;

export function ResumeWithAnswer(arg1:string):Promise<void>;

export function ResumeWithChoice(arg1:number):Promise<void>;

export function RevokeToolPermissionGrant(arg1:string,arg2:string):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SessionCtxEngine(arg1:string):Promise<agentctx.Engine>;

export function SessionStreamingState(arg1:string):Promise<model.StreamingState>;

export function SessionTimeline(arg1:string):Promise<agentctx.TimelineCollector>;

export function SetActiveSessionID(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDependencies(arg1:sandbox.SandboxManager,arg2:agentctx.Engine):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function SetOnAgentDone(arg1:any):Promise<void>;

export function SetSessionService(arg1:service.SessionService):Promise<void>;

export function StopGeneration():Promise<void>;

export function StopRuntimeTask(arg1:string):Promise<tools.RuntimeTaskSnapshot>;

export function StopSessionGeneration(arg1:string):Promise<void>;

export function StreamingState():Promise<model.StreamingState>;

export function Timeline():Promise<agentctx.TimelineCollector>;

export function UpdateSandbox(arg1:sandbox.SandboxManager):Promise<void>;

export function WaitForSessionDone(arg1:string,arg2:time.Duration):Promise<void>;
