// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildRunners() {
  return window['go']['service']['ChatService']['BuildRunners']();
}

export function ClearHistory() {
  return window['go']['service']['ChatService']['ClearHistory']();
}

export function CtxEngine() {
  return window['go']['service']['ChatService']['CtxEngine']();
}

export function GetActiveSessionID() {
  return window['go']['service']['ChatService']['GetActiveSessionID']();
}

export function GetMode() {
  return window['go']['service']['ChatService']['GetMode']();
}

export function GetOrCreateRun(arg1) {
  return window['go']['service']['ChatService']['GetOrCreateRun'](arg1);
}

export function GetSessionRunSnapshot(arg1) {
  return window['go']['service']['ChatService']['GetSessionRunSnapshot'](arg1);
}

export function InvalidateRunner() {
  return window['go']['service']['ChatService']['InvalidateRunner']();
}

export function IsRunning() {
  return window['go']['service']['ChatService']['IsRunning']();
}

export function IsSessionRunning(arg1) {
  return window['go']['service']['ChatService']['IsSessionRunning'](arg1);
}

export function RemoveSession(arg1) {
  return window['go']['service']['ChatService']['RemoveSession'](arg1);
}

export function ResumeWithAnswer(arg1) {
  return window['go']['service']['ChatService']['ResumeWithAnswer'](arg1);
}

export function ResumeWithChoice(arg1) {
  return window['go']['service']['ChatService']['ResumeWithChoice'](arg1);
}

export function SendMessage(arg1, arg2) {
  return window['go']['service']['ChatService']['SendMessage'](arg1, arg2);
}

export function SessionCtxEngine(arg1) {
  return window['go']['service']['ChatService']['SessionCtxEngine'](arg1);
}

export function SessionStreamingState(arg1) {
  return window['go']['service']['ChatService']['SessionStreamingState'](arg1);
}

export function SessionTimeline(arg1) {
  return window['go']['service']['ChatService']['SessionTimeline'](arg1);
}

export function SetActiveSessionID(arg1) {
  return window['go']['service']['ChatService']['SetActiveSessionID'](arg1);
}

export function SetContext(arg1) {
  return window['go']['service']['ChatService']['SetContext'](arg1);
}

export function SetDependencies(arg1, arg2) {
  return window['go']['service']['ChatService']['SetDependencies'](arg1, arg2);
}

export function SetMode(arg1) {
  return window['go']['service']['ChatService']['SetMode'](arg1);
}

export function SetOnAgentDone(arg1) {
  return window['go']['service']['ChatService']['SetOnAgentDone'](arg1);
}

export function SetSessionService(arg1) {
  return window['go']['service']['ChatService']['SetSessionService'](arg1);
}

export function StopGeneration() {
  return window['go']['service']['ChatService']['StopGeneration']();
}

export function StopSessionGeneration(arg1) {
  return window['go']['service']['ChatService']['StopSessionGeneration'](arg1);
}

export function StreamingState() {
  return window['go']['service']['ChatService']['StreamingState']();
}

export function Timeline() {
  return window['go']['service']['ChatService']['Timeline']();
}

export function UpdateSandbox(arg1) {
  return window['go']['service']['ChatService']['UpdateSandbox'](arg1);
}

export function WaitForSessionDone(arg1, arg2) {
  return window['go']['service']['ChatService']['WaitForSessionDone'](arg1, arg2);
}
