// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {sandbox} from '../models';
import {agentctx} from '../models';
import {service} from '../models';
import {model} from '../models';

export function BuildRunners():Promise<void>;

export function ClearHistory():Promise<void>;

export function GetMode():Promise<string>;

export function InvalidateRunner():Promise<void>;

export function ResumeWithAnswer(arg1:string):Promise<void>;

export function ResumeWithChoice(arg1:number):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDependencies(arg1:sandbox.SandboxManager,arg2:agentctx.Engine):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function SetOnAgentDone(arg1:any):Promise<void>;

export function SetSessionService(arg1:service.SessionService):Promise<void>;

export function StopGeneration():Promise<void>;

export function StreamingState():Promise<model.StreamingState>;

export function Timeline():Promise<agentctx.TimelineCollector>;

export function UpdateSandbox(arg1:sandbox.SandboxManager):Promise<void>;
