// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildRunners() {
  return window['go']['service']['ChatService']['BuildRunners']();
}

export function ClearHistory() {
  return window['go']['service']['ChatService']['ClearHistory']();
}

export function GetMode() {
  return window['go']['service']['ChatService']['GetMode']();
}

export function InvalidateRunner() {
  return window['go']['service']['ChatService']['InvalidateRunner']();
}

export function ResumeWithAnswer(arg1) {
  return window['go']['service']['ChatService']['ResumeWithAnswer'](arg1);
}

export function ResumeWithChoice(arg1) {
  return window['go']['service']['ChatService']['ResumeWithChoice'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['service']['ChatService']['SendMessage'](arg1);
}

export function SetContext(arg1) {
  return window['go']['service']['ChatService']['SetContext'](arg1);
}

export function SetDependencies(arg1, arg2) {
  return window['go']['service']['ChatService']['SetDependencies'](arg1, arg2);
}

export function SetMode(arg1) {
  return window['go']['service']['ChatService']['SetMode'](arg1);
}

export function SetOnAgentDone(arg1) {
  return window['go']['service']['ChatService']['SetOnAgentDone'](arg1);
}

export function SetSessionService(arg1) {
  return window['go']['service']['ChatService']['SetSessionService'](arg1);
}

export function StopGeneration() {
  return window['go']['service']['ChatService']['StopGeneration']();
}

export function StreamingState() {
  return window['go']['service']['ChatService']['StreamingState']();
}

export function Timeline() {
  return window['go']['service']['ChatService']['Timeline']();
}

export function UpdateSandbox(arg1) {
  return window['go']['service']['ChatService']['UpdateSandbox'](arg1);
}
