// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {agentctx} from '../models';
import {service} from '../models';
import {model} from '../models';
import {context} from '../models';
import {sandbox} from '../models';
import {time} from '../models';

export function BuildRunners():Promise<void>;

export function ClearHistory():Promise<void>;

export function CtxEngine():Promise<agentctx.Engine>;

export function GetActiveSessionID():Promise<string>;

export function GetMode():Promise<string>;

export function GetOrCreateRun(arg1:string):Promise<service.SessionRun>;

export function GetSessionRunSnapshot(arg1:string):Promise<boolean>;

export function InvalidateRunner():Promise<void>;

export function IsRunning():Promise<boolean>;

export function IsSessionRunning(arg1:string):Promise<boolean>;

export function RemoveSession(arg1:string):Promise<void>;

export function ResumeWithAnswer(arg1:string):Promise<void>;

export function ResumeWithChoice(arg1:number):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SessionCtxEngine(arg1:string):Promise<agentctx.Engine>;

export function SessionStreamingState(arg1:string):Promise<model.StreamingState>;

export function SessionTimeline(arg1:string):Promise<agentctx.TimelineCollector>;

export function SetActiveSessionID(arg1:string):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetDependencies(arg1:sandbox.SandboxManager,arg2:agentctx.Engine):Promise<void>;

export function SetMode(arg1:string):Promise<void>;

export function SetOnAgentDone(arg1:any):Promise<void>;

export function SetSessionService(arg1:service.SessionService):Promise<void>;

export function StopGeneration():Promise<void>;

export function StopSessionGeneration(arg1:string):Promise<void>;

export function StreamingState():Promise<model.StreamingState>;

export function Timeline():Promise<agentctx.TimelineCollector>;

export function UpdateSandbox(arg1:sandbox.SandboxManager):Promise<void>;

export function WaitForSessionDone(arg1:string,arg2:time.Duration):Promise<void>;
