// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {context} from '../models';
import {service} from '../models';

export function ActivateContainer(arg1:string):Promise<void>;

export function CreateContainer():Promise<void>;

export function DeactivateContainer():Promise<void>;

export function DestroyContainer(arg1:string):Promise<void>;

export function ListContainers():Promise<Array<model.Container>>;

export function RefreshContainerStatus(arg1:string):Promise<model.Container>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetSessionService(arg1:service.SessionService):Promise<void>;

export function StartContainer(arg1:string):Promise<void>;

export function StopContainer(arg1:string):Promise<void>;
