// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DestroyContainer(arg1) {
  return window['go']['service']['ContainerService']['DestroyContainer'](arg1);
}

export function ListContainers() {
  return window['go']['service']['ContainerService']['ListContainers']();
}

export function RefreshContainerStatus(arg1) {
  return window['go']['service']['ContainerService']['RefreshContainerStatus'](arg1);
}

export function SetContext(arg1) {
  return window['go']['service']['ContainerService']['SetContext'](arg1);
}

export function SetSessionService(arg1) {
  return window['go']['service']['ContainerService']['SetSessionService'](arg1);
}

export function StartContainer(arg1) {
  return window['go']['service']['ContainerService']['StartContainer'](arg1);
}

export function StopContainer(arg1) {
  return window['go']['service']['ContainerService']['StopContainer'](arg1);
}
