// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {context} from '../models';

export function DownloadFile(arg1:string):Promise<void>;

export function ListWorkspaceFiles():Promise<Array<service.FileInfoDTO>>;

export function ReadFilePreview(arg1:string):Promise<string>;

export function SelectAndUploadFile():Promise<service.FileInfoDTO>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetSessionService(arg1:service.SessionService):Promise<void>;

export function UploadFile(arg1:string):Promise<service.FileInfoDTO>;
