// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupSandboxTmp() {
  return window['go']['service']['FileService']['CleanupSandboxTmp']();
}

export function DownloadFile(arg1) {
  return window['go']['service']['FileService']['DownloadFile'](arg1);
}

export function GetWorkspaceInfo() {
  return window['go']['service']['FileService']['GetWorkspaceInfo']();
}

export function ListWorkspaceFiles() {
  return window['go']['service']['FileService']['ListWorkspaceFiles']();
}

export function ReadFilePreview(arg1) {
  return window['go']['service']['FileService']['ReadFilePreview'](arg1);
}

export function SelectAndUploadFile() {
  return window['go']['service']['FileService']['SelectAndUploadFile']();
}

export function SetContext(arg1) {
  return window['go']['service']['FileService']['SetContext'](arg1);
}

export function SetSessionService(arg1) {
  return window['go']['service']['FileService']['SetSessionService'](arg1);
}

export function UploadFile(arg1) {
  return window['go']['service']['FileService']['UploadFile'](arg1);
}
