// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateContainer(arg1) {
  return window['go']['service']['SandboxService']['ActivateContainer'](arg1);
}

export function ActiveContainerRegID() {
  return window['go']['service']['SandboxService']['ActiveContainerRegID']();
}

export function Connect() {
  return window['go']['service']['SandboxService']['Connect']();
}

export function ConnectExisting(arg1) {
  return window['go']['service']['SandboxService']['ConnectExisting'](arg1);
}

export function ConnectSSH() {
  return window['go']['service']['SandboxService']['ConnectSSH']();
}

export function CreateAndActivateContainer() {
  return window['go']['service']['SandboxService']['CreateAndActivateContainer']();
}

export function DeactivateContainer() {
  return window['go']['service']['SandboxService']['DeactivateContainer']();
}

export function Disconnect() {
  return window['go']['service']['SandboxService']['Disconnect']();
}

export function DisconnectAndDestroy() {
  return window['go']['service']['SandboxService']['DisconnectAndDestroy']();
}

export function DisconnectSSH() {
  return window['go']['service']['SandboxService']['DisconnectSSH']();
}

export function GetStatus() {
  return window['go']['service']['SandboxService']['GetStatus']();
}

export function Manager() {
  return window['go']['service']['SandboxService']['Manager']();
}

export function SetContext(arg1) {
  return window['go']['service']['SandboxService']['SetContext'](arg1);
}

export function SetOnConnect(arg1) {
  return window['go']['service']['SandboxService']['SetOnConnect'](arg1);
}

export function SetOnContainerBound(arg1) {
  return window['go']['service']['SandboxService']['SetOnContainerBound'](arg1);
}

export function SetOnContainerDeactivated(arg1) {
  return window['go']['service']['SandboxService']['SetOnContainerDeactivated'](arg1);
}

export function SetSessionService(arg1) {
  return window['go']['service']['SandboxService']['SetSessionService'](arg1);
}

export function StartHealthMonitor(arg1) {
  return window['go']['service']['SandboxService']['StartHealthMonitor'](arg1);
}
