// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {service} from '../models';
import {sandbox} from '../models';
import {context} from '../models';

export function ActiveContainerRegID():Promise<string>;

export function Connect():Promise<void>;

export function ConnectExisting(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function DisconnectAndDestroy():Promise<void>;

export function GetStatus():Promise<service.SandboxStatusDTO>;

export function Manager():Promise<sandbox.SandboxManager>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetOnConnect(arg1:any):Promise<void>;

export function SetOnContainerBound(arg1:any):Promise<void>;

export function StartHealthMonitor(arg1:context.Context):Promise<void>;
