// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {service} from '../models';
import {context} from '../models';
import {agentctx} from '../models';

export function BindContainer(arg1:string,arg2:string):Promise<void>;

export function CreateSession(arg1:string):Promise<model.Session>;

export function DeleteSession(arg1:string):Promise<void>;

export function EnsureDefaultSession():Promise<void>;

export function GetActiveSession():Promise<model.Session>;

export function GetActiveSessionMessages():Promise<Array<model.PersistedMessage>>;

export function GetBoundContainerID():Promise<string>;

export function GetWorkspacePath():Promise<string>;

export function ListSessions():Promise<Array<model.Session>>;

export function ListSessionsEnriched():Promise<Array<service.EnrichedSession>>;

export function LoadChatDisplay():Promise<string>;

export function LoadSessionData():Promise<model.SessionData>;

export function RenameSession(arg1:string,arg2:string):Promise<void>;

export function SaveChatDisplay(arg1:string):Promise<void>;

export function SaveCurrentSession():Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetChatService(arg1:service.ChatService):Promise<void>;

export function SetCtxEngine(arg1:agentctx.Engine):Promise<void>;

export function SetOnDestroyContainer(arg1:any):Promise<void>;

export function SetOnSessionSwitch(arg1:any):Promise<void>;

export function SwitchSession(arg1:string):Promise<void>;
