// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BindContainer(arg1, arg2) {
  return window['go']['service']['SessionService']['BindContainer'](arg1, arg2);
}

export function CreateSession(arg1) {
  return window['go']['service']['SessionService']['CreateSession'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['service']['SessionService']['DeleteSession'](arg1);
}

export function EnsureDefaultSession() {
  return window['go']['service']['SessionService']['EnsureDefaultSession']();
}

export function GetActiveSession() {
  return window['go']['service']['SessionService']['GetActiveSession']();
}

export function GetActiveSessionMessages() {
  return window['go']['service']['SessionService']['GetActiveSessionMessages']();
}

export function GetBoundContainerID() {
  return window['go']['service']['SessionService']['GetBoundContainerID']();
}

export function GetWorkspacePath() {
  return window['go']['service']['SessionService']['GetWorkspacePath']();
}

export function ListSessions() {
  return window['go']['service']['SessionService']['ListSessions']();
}

export function ListSessionsEnriched() {
  return window['go']['service']['SessionService']['ListSessionsEnriched']();
}

export function LoadChatDisplay() {
  return window['go']['service']['SessionService']['LoadChatDisplay']();
}

export function RenameSession(arg1, arg2) {
  return window['go']['service']['SessionService']['RenameSession'](arg1, arg2);
}

export function SaveChatDisplay(arg1) {
  return window['go']['service']['SessionService']['SaveChatDisplay'](arg1);
}

export function SaveCurrentSession() {
  return window['go']['service']['SessionService']['SaveCurrentSession']();
}

export function SetContext(arg1) {
  return window['go']['service']['SessionService']['SetContext'](arg1);
}

export function SetCtxEngine(arg1) {
  return window['go']['service']['SessionService']['SetCtxEngine'](arg1);
}

export function SetOnDestroyContainer(arg1) {
  return window['go']['service']['SessionService']['SetOnDestroyContainer'](arg1);
}

export function SetOnSessionSwitch(arg1) {
  return window['go']['service']['SessionService']['SetOnSessionSwitch'](arg1);
}

export function SwitchSession(arg1) {
  return window['go']['service']['SessionService']['SwitchSession'](arg1);
}
