// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {sandbox} from '../models';
import {context} from '../models';

export function CheckSandboxRuntime(arg1:config.AppConfig):Promise<sandbox.RuntimeCheckResult>;

export function GetSettings():Promise<config.AppConfig>;

export function InstallSandboxRuntime(arg1:config.AppConfig):Promise<sandbox.RuntimeInstallResult>;

export function SaveSettings(arg1:config.AppConfig):Promise<void>;

export function SetContext(arg1:context.Context):Promise<void>;

export function SetOnSettingsSave(arg1:any):Promise<void>;

export function TestLLMConnection(arg1:config.LLMConfig):Promise<void>;

export function TestSSHConnection(arg1:config.SSHConfig):Promise<void>;
