// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetSettings() {
  return window['go']['service']['SettingsService']['GetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['service']['SettingsService']['SaveSettings'](arg1);
}

export function SetContext(arg1) {
  return window['go']['service']['SettingsService']['SetContext'](arg1);
}

export function SetOnSettingsSave(arg1) {
  return window['go']['service']['SettingsService']['SetOnSettingsSave'](arg1);
}

export function TestLLMConnection(arg1) {
  return window['go']['service']['SettingsService']['TestLLMConnection'](arg1);
}

export function TestSSHConnection(arg1) {
  return window['go']['service']['SettingsService']['TestSSHConnection'](arg1);
}
