import type { Component } from 'vue'
import {
  AlertTriangle,
  Bot,
  Boxes,
  Check,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleStop,
  Clock,
  Code2,
  Command,
  Copy,
  Download,
  ExternalLink,
  Eye,
  File,
  FileDiff,
  Folder,
  GitBranch,
  Globe2,
  KeyRound,
  Link2,
  Lock,
  MessageSquare,
  Network,
  Play,
  Plus,
  RefreshCw,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  SquareTerminal,
  Trash2,
  Upload,
  X,
} from 'lucide-vue-next'

export const sxIconMap = {
  ai: Bot,
  broom: Sparkles,
  check: Check,
  chevron: ChevronRight,
  close: X,
  command: Command,
  connect: Link2,
  copy: Copy,
  diff: FileDiff,
  disconnect: Network,
  download: Download,
  error: CircleAlert,
  external: ExternalLink,
  eye: Eye,
  file: File,
  folder: Folder,
  git: GitBranch,
  info: CircleHelp,
  key: KeyRound,
  lock: Lock,
  lsp: Code2,
  mcp: Boxes,
  permission: ShieldCheck,
  play: Play,
  plus: Plus,
  refresh: RefreshCw,
  runtime: CircleCheck,
  sandbox: Boxes,
  search: Search,
  session: MessageSquare,
  settings: Settings,
  stop: CircleStop,
  tasks: AlertTriangle,
  terminal: SquareTerminal,
  trash: Trash2,
  upload: Upload,
  warn: AlertTriangle,
  web: Globe2,
  worktree: GitBranch,
  workspace: Folder,
  x: X,
  clock: Clock,
} satisfies Record<string, Component>

export type SxIconName = keyof typeof sxIconMap

export function resolveSxIcon(name?: SxIconName | string): Component {
  return sxIconMap[(name || 'info') as SxIconName] || CircleHelp
}
